### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by PanderMusubi** [clach04/fake_vcgencmd#3]
Can you make a tagged release so we can use it in automated processes, e.g. build for Armbian?

**Comment by clach04** [comment]
@PanderMusubi I love Armbian!

https://github.com/clach04/fake_vcgencmd/releases/tag/0.0.1 created.

**Comment by PanderMusubi** [comment]
Thanks. See https://github.com/armbian/build/pull/5095

**Comment by PanderMusubi** [comment]
@clach04 what board do you have Armbian running on? On those boards, does vcgencmd work? Currently, I only have added it to the build for the Pine 64.

**Comment by clach04** [comment]
* x86 machines
* rock64 - armbian and non-armbian
* odroid

Not had chance to try on Orange Pi and Potato yet.

**Comment by PanderMusubi** [comment]
Sorry to use this issue for this, which of the boards listed in https://github.com/armbian/build/tree/main/config/boards can I add that fake vcgencmd gets installed during the build? In other words, are you sure (tested) that it will work when I add https://github.com/armbian/build/pull/5095/commits/f2788d5a997685a8b22fd9d5cef814ab8be1f2bf ? I can provide you with custom builds to download or a simple command to build an image you can test.

**Comment by clach04** [comment]
@PanderMusubi I wont have access to do a test for a while BUT from memory I can confirm:

* https://github.com/armbian/build/blob/main/config/boards/rock64.conf
* https://github.com/armbian/build/blob/main/config/boards/odroidxu4.conf

What  can't guarantee is that the odroid one was unmodified fake_vcgencmd (there is a remote chance the thermal value paths are different).
