### ISSUE TITLE
Fix potential temp file vulnerability

### ISSUE THREAD

**Issue by PanderMusubi** [clach04/fake_vcgencmd#5]
Can you fix this https://github.com/armbian/build/pull/5095#issuecomment-1521626783

Perhaps comment out all and remove the exit.

**Comment by clach04** [comment]
from https://github.com/armbian/build/pull/5095#issuecomment-1521725673

> It's only purpose is to avoid temp file vulnerabilities in scripts. You pull in code from somewhere that's not under your own control and the exit statement might vanish at any time without anyone noticing. That's almost recipe for disaster :)

**Comment by PanderMusubi** [comment]
Thanks. Can you make a new release as Armbian pulls the files based on release number.

**Comment by clach04** [comment]
https://github.com/clach04/fake_vcgencmd/releases/tag/0.0.2

**Comment by PanderMusubi** [comment]
Thanks. FYI, the new version is also fine when inspected with `checkbashisms vcgencmd`. Handy script for also next versions. See also https://github.com/armbian/build/pull/5100 and https://github.com/clach04/fake_vcgencmd/pull/6
